# Copyright (c) 1993-1995 Argonaut Technologies Limited. All rights reserved.
#
# $Id: makefile 1.1 1997/12/10 17:16:38 jon Exp $
# $Locker: $
#
# Makefile for BRender V1 Database
#
.IMPORT: BR_SOURCE_DIR BR_MAKEFILE BR_TARGET_DIR BR_MAKE_DIR

LIB_PART:=brdb
TARGET_TYPE:=LIB

## Base library object files
##
OBJS_C=\
    $(BLD_DIR)/actsupt$(OBJ_EXT)\
    $(BLD_DIR)/custsupt$(OBJ_EXT)\
    $(BLD_DIR)/dbsetup$(OBJ_EXT)\
    $(BLD_DIR)/def_mat$(OBJ_EXT)\
    $(BLD_DIR)/def_mdl$(OBJ_EXT)\
    $(BLD_DIR)/def_otab$(OBJ_EXT)\
    $(BLD_DIR)/enables$(OBJ_EXT)\
    $(BLD_DIR)/ffhooks$(OBJ_EXT)\
    $(BLD_DIR)/matsupt$(OBJ_EXT)\
    $(BLD_DIR)/modrend$(OBJ_EXT)\
    $(BLD_DIR)/modsupt$(OBJ_EXT)\
    $(BLD_DIR)/otable$(OBJ_EXT)\
    $(BLD_DIR)/pick$(OBJ_EXT)\
    $(BLD_DIR)/prelight$(OBJ_EXT)\
    $(BLD_DIR)/prepmap$(OBJ_EXT)\
    $(BLD_DIR)/prepmatl$(OBJ_EXT)\
    $(BLD_DIR)/prepmesh$(OBJ_EXT)\
    $(BLD_DIR)/preptab$(OBJ_EXT)\
    $(BLD_DIR)/regsupt$(OBJ_EXT)\
    $(BLD_DIR)/render$(OBJ_EXT)\
    $(BLD_DIR)/v1dbfile$(OBJ_EXT)\
    $(BLD_DIR)/dbquery$(OBJ_EXT)\
#    $(BLD_DIR)/ot_trav$(OBJ_EXT)\
#    $(BLD_DIR)/query$(OBJ_EXT)\


OBJS_ASM=\


.INCLUDE: $(BR_MAKE_DIR)/$(BR_MAKEFILE)

