;; Copyright (c) 1992,1994-1995 Argonaut Technologies Limited. All rights reserved.
;;
;; $Id: magicsym.asm 1.1 1997/12/10 16:46:06 jon Exp $
;; $Locker: $
;;
;; Define any magic symbols generated by compilers - needed when not
;; linking against vendors runtime
;;
	.486p
	.model flat

ifdef __DRIVER__
ifdef __WATCOMC__

	.data
	; Supress Watcom RTL gubbins
	;

	public __8087
	public __init_387_emulator
	public _fltused_
	public _fltused_
	public __chipbug

__chipbug		dd	0
__8087			dd	0
__init_387_emulator	dd	0
_fltused_		dd	0

	.code
	public __CHK

__CHK:
		ret 004
endif
endif
  	end


