;; Copyright (c) 1992,1994-1995 Argonaut Technologies Limited. All rights reserved.
;;
;; $Id: magicsym.asm 1.1 1997/12/10 16:47:13 jon Exp $
;; $Locker: $
;;
;; Define any magic symbols generated by compilers - needed when not
;; linking against vendors runtime
;;
	.486p
	.model flat

ifdef __DRIVER__

ifdef __WATCOMC__

	.data
	; Supress Watcom RTL gubbins
	;

	public __8087
	public __init_387_emulator
	public _fltused_
	public _fltused_
	public __chipbug

__chipbug		dd	0
__8087			dd	0
__init_387_emulator	dd	0
_fltused_		dd	0

	.code
if 0
                PUBLIC  __CHP 

__CHP:          push    eax
                fstcw   [esp]
                wait    
                push    dword ptr [esp]
                mov     byte ptr 1[esp],01fh
                fldcw   [esp]
                frndint 
                fldcw   4[esp]
                wait    
                lea     esp,8[esp]
                ret
endif
if 1
		public __fptan_chk
__fptan_chk:	ret

		public __fpatan_wrap
__fpatan_wrap:	ret

		public __math87_err_
__math87_err_:	ret
endif
endif

ifdef __VISUALC__

	.data
	; Supress Visual C++ runtime
	;

	public __fltused

__fltused		dd	0
endif

endif
  	end


