; Copyright (c) 1992,1993-1996 Argonaut Technologies Limited. All rights reserved.
;
; $Id: setupdat.inc 1.1 1997/12/10 16:48:15 jon Exp $
; $Locker: $
;
; Common data for setup code
;
		externdef xconv_d16_12:qword
		externdef xconv_d16_m:qword
		externdef fconv_d16_12:qword
		externdef fconv_d16_m:qword
		externdef fp_one:dword
		externdef fp_one_fixed:dword
		externdef fp_rone_fixed:dword
		externdef fp_conv_dm4:dword
		externdef fp_conv_d:dword
		externdef fp_conv_d8:dword
		externdef fp_conv_d12:dword
		externdef fp_conv_d16:dword
		externdef fp_conv_d24:dword
		externdef fp_conv_sm16:dword
		externdef fp_conv_sm8:dword
		externdef fp_conv_s:dword
		externdef fp_conv_s8:dword
		externdef sort_table_1:dword
		externdef sort_table_0:dword
		externdef sort_table_2:dword
		externdef flip_table:dword

