# Copyright (c) 1993-1995 Argonaut Technologies Limited. All rights reserved.
#
# $Id: makefile 1.2 1998/07/16 13:36:49 jon Exp $
# $Locker: $
#
# Makefile for BRender core includes
#

.IMPORT: BR_SOURCE_DIR BR_MAKEFILE BR_TARGET_DIR BR_MAKE_DIR

.INCLUDE: $(BR_MAKE_DIR)/macros.mak

EXPORT_INCLUDES=\
	$(INC_DIR)/actor.h\
	$(INC_DIR)/assocarr.h\
	$(INC_DIR)/assoca_p.h\
	$(INC_DIR)/angles.h\
	$(INC_DIR)/brdiag.h\
	$(INC_DIR)/brender.h\
	$(INC_DIR)/brerror.h\
	$(INC_DIR)/brfile.h\
	$(INC_DIR)/brfont.h\
	$(INC_DIR)/brlimits.h\
	$(INC_DIR)/brmem.h\
	$(INC_DIR)/brv1db.h\
	$(INC_DIR)/camera.h\
	$(INC_DIR)/colour.h\
	$(INC_DIR)/compend.h\
	$(INC_DIR)/compiler.h\
	$(INC_DIR)/custsupt.h\
	$(INC_DIR)/dmyifix.h\
	$(INC_DIR)/fixed.h\
	$(INC_DIR)/fw_p.h\
	$(INC_DIR)/g386ifix.h\
	$(INC_DIR)/light.h\
	$(INC_DIR)/material.h\
	$(INC_DIR)/math_p.h\
	$(INC_DIR)/math_x.h\
	$(INC_DIR)/matrix.h\
	$(INC_DIR)/model.h\
	$(INC_DIR)/mscifix.h\
	$(INC_DIR)/mscimath.h\
	$(INC_DIR)/order.h\
	$(INC_DIR)/pixelmap.h\
	$(INC_DIR)/pm_p.h\
	$(INC_DIR)/pool.h\
	$(INC_DIR)/proifix.h\
	$(INC_DIR)/quat.h\
	$(INC_DIR)/render.h\
	$(INC_DIR)/scalar.h\
	$(INC_DIR)/syscn_p.h\
	$(INC_DIR)/token.h\
	$(INC_DIR)/transfrm.h\
	$(INC_DIR)/v1db_p.h\
	$(INC_DIR)/vecfns.h\
    $(INC_DIR)/brvector.h\
	$(INC_DIR)/wtcifix.h\

target depend includes: $(EXPORT_INCLUDES)

