print "/*\n * Generated by maptodef.pl\n */\n";

while(<>) {
	if(/^\s*[0-9A-Fa-f]{4}:([0-9A-Fa-f]{4})\*?\s+(\w+)/) {
		$symbols{$2} = hex($1);
	}
}

foreach $s (sort(keys(%symbols))) {
	printf "#define SYM%-32s0x%04x\n",$s,$symbols{$s};
}

